apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ns.yaml
  - kube-prometheus.yaml
  - loki.yaml
  - tempo.yaml
  - otel-collector.yaml
  - grafana-ingressroute.yaml
  - argocd-monitor.yaml
  - dashboards/infra-executiva.yaml
  - dashboards/argocd-sync.yaml
