---
- name: Atualizar cache do APT
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Instalar pacotes essenciais e suporte a Python
  apt:
    name:
      - curl
      - git
      - ufw
      - open-iscsi
      - iptables-persistent
      - python3-pip
      - python3-dev
    state: present

- name: Liberar tráfego interno no iptables (Exigência OCI)
  iptables:
    chain: INPUT
    action: insert
    rule_num: 1
    source: 10.0.0.0/16
    jump: ACCEPT

- name: Salvar regras do firewall
  command: netfilter-persistent save
