---
- name: Configurar Firewall OS (Oracle/Ubuntu) para permitir K3s
  ansible.builtin.iptables:
    chain: "{{ item.chain }}"
    source: "{{ item.source }}"
    protocol: "{{ item.protocol | default(omit) }}"
    destination_port: "{{ item.port | default(omit) }}"
    jump: ACCEPT
    action: insert
    rule_num: 1
  loop:
    - { chain: "INPUT", source: "10.42.0.0/16" }
    - { chain: "FORWARD", source: "10.42.0.0/16" }
    - { chain: "INPUT", source: "10.43.0.0/16" }
    - { chain: "FORWARD", source: "10.43.0.0/16" }
    - { chain: "INPUT", source: "10.0.0.0/16" }
    - { chain: "FORWARD", source: "10.0.0.0/16" }
    - {
        chain: "INPUT",
        source: "{{ meu_ip_adm }}",
        protocol: "tcp",
        port: "6443",
      }

- name: Salvar regras do firewall local para persistir após reboot
  ansible.builtin.command: netfilter-persistent save
