---
- name: Garantir política ACCEPT no FORWARD (Desobstruir K3s)
  ansible.builtin.iptables:
    chain: FORWARD
    policy: ACCEPT

- name: Limpar firewall nativo conflitante da Oracle
  ansible.builtin.command: iptables -F

- name: Garantir acesso à API do K3s apenas para o IP do Administrador
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    source: "{{ meu_ip_adm }}"
    destination_port: "6443"
    jump: ACCEPT

- name: Salvar estado do firewall
  ansible.builtin.command: netfilter-persistent save
