---
- name: Configurações base em todos os nós
  hosts: all
  become: true
  roles:
    - common

- name: Instalação do K3s Master
  hosts: k3s_master
  become: true
  roles:
    - k3s_master

- name: Instalação do K3s Worker
  hosts: k3s_worker
  become: true
  roles:
    - k3s_worker
