---
- name: Configurações base em todos os nós
  hosts: all
  become: true
  roles:
    - common

- name: Configurações base em todos os nós
  hosts: all
  become: true
  roles:
    - firewall

- name: Instalação do K3s Master
  hosts: k3s_master
  become: true
  roles:
    - k3s_master

- name: Instalação do K3s Worker
  hosts: k3s_worker
  become: true
  roles:
    - k3s_worker

- name: Instalação e Configuração do ArgoCD (GitOps)
  hosts: k3s_master
  become: true
  roles:
    - argocd
