apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - infra/argo
  - infra/observability
  # apps/ entra aqui quando a primeira app real pousar (cada app com sua kustomization).
