name: "Terraform OCI Pipeline"

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Ação (plan ou apply)"
        required: true
        default: "plan"
        type: choice
        options:
          - plan
          - apply

jobs:
  terraform:
    name: "Terraform Exec"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform

    env:
      TF_VAR_tenancy_ocid: ${{ secrets.OCI_TENANCY_OCID }}
      TF_VAR_user_ocid: ${{ secrets.OCI_USER_OCID }}
      TF_VAR_fingerprint: ${{ secrets.OCI_FINGERPRINT }}
      TF_VAR_private_key: ${{ secrets.OCI_PRIVATE_KEY }}
      TF_VAR_region: ${{ secrets.OCI_REGION }}
      # Variáveis do Projeto (Injetadas)
      TF_VAR_availability_domain: ${{ vars.TF_VAR_AVAILABILITY_DOMAIN }}
      TF_VAR_image_id: ${{ vars.TF_VAR_IMAGE_ID }}

      TF_VAR_compartment_id: ${{ secrets.TF_VAR_COMPARTMENT_ID }}
      TF_VAR_ssh_public_key: ${{ secrets.TF_VAR_SSH_PUBLIC_KEY }}
      TF_VAR_meu_ip: ${{ secrets.TF_VAR_MEU_IP }}

      TF_VAR_meu_ip_adm: ${{ secrets.TF_VAR_MEU_IP_ADM }}

      # Configurações de Hardware (Não sensíveis, hardcoded)
      TF_VAR_instance_shape: "VM.Standard.A1.Flex"
      TF_VAR_ocpus_per_node: 2
      TF_VAR_memory_per_node: 12

      # Cloudflare DNS GitOps (token com permissão Edit zone DNS)
      TF_VAR_cloudflare_api_token: ${{ secrets.TF_VAR_CLOUDFLARE_API_TOKEN }}

    steps:
      - name: "Checkout do código"
        uses: actions/checkout@v4

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.16.1"

      - name: "Terraform Init"
        run: |
          terraform init \
            -backend-config="address=${{ secrets.TF_BACKEND_PAR_URL }}" \
            -backend-config="update_method=PUT"

      - name: "Terraform Plan"
        if: github.event.inputs.action == 'plan'
        run: terraform plan -input=false

      - name: "Terraform Apply"
        if: github.event.inputs.action == 'apply'
        run: terraform apply -auto-approve -input=false
